# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdlx < Formula
  desc "Code Lexica command-line tool"
  homepage "https://codelexica.com"
  version "1.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v1.1.0/cdlx_1.1.0_darwin_amd64.tar.gz"
      sha256 "be07d1b14a4a687fe015d408a448dc0e4f930bd43ab1a9dc7d15ce7479faf68f"

      define_method(:install) do
        bin.install "cdlx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v1.1.0/cdlx_1.1.0_darwin_arm64.tar.gz"
      sha256 "8e15b9da409646bb612bb56da5a5cd6e4acafb6813850865406fcb19d816d39e"

      define_method(:install) do
        bin.install "cdlx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v1.1.0/cdlx_1.1.0_linux_amd64.tar.gz"
      sha256 "4099f7d3aff463e1f839c70648c72a950296621d62a52da41e5932c779bb07f0"
      define_method(:install) do
        bin.install "cdlx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v1.1.0/cdlx_1.1.0_linux_arm64.tar.gz"
      sha256 "757cdb950fdee1f175c6ef8df3e0bdb8889c9eb226370e979e9e46c93f785fe5"
      define_method(:install) do
        bin.install "cdlx"
      end
    end
  end

  test do
    system "#{bin}/cdlx version"
  end
end
