# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdlx < Formula
  desc "Code Lexica command-line tool"
  homepage "https://codelexica.com"
  version "2.1.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v2.1.1/cdlx_2.1.1_darwin_amd64.tar.gz"
      sha256 "9fdf165534849d7c215706ee16196d773292beb5a55baf9684417fc2752ae706"

      define_method(:install) do
        bin.install "cdlx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v2.1.1/cdlx_2.1.1_darwin_arm64.tar.gz"
      sha256 "e1b20b5c277eba3c4082c9fe120b62ad3a7bd91d0e10eb346c2e7aa07f7c8523"

      define_method(:install) do
        bin.install "cdlx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v2.1.1/cdlx_2.1.1_linux_amd64.tar.gz"
      sha256 "578dd04d7347596f3ee6ddd1884bb75cbbd0b1f1dd9ed32fc7c7501e108e22ed"
      define_method(:install) do
        bin.install "cdlx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codelexica/cdlx-dist/releases/download/v2.1.1/cdlx_2.1.1_linux_arm64.tar.gz"
      sha256 "b4812f38794a7b1e09b20627f77db84e9fbdf5163765f105120c6a3579bbeda9"
      define_method(:install) do
        bin.install "cdlx"
      end
    end
  end

  test do
    system "#{bin}/cdlx version"
  end
end
